meta_product_name: "Gimme Shelter"
meta_title: "Gimme Shelter - Give shelter to a homeless person today"
meta_description: "Quickly and easily find accomodation for homeless people in your area"
meta_image: "cover.jpg"
