  Hostel.destroy_all
  Service.destroy_all

  puts "creating hostels and services"





 # Hostel.create!(:name=>"Saint James Backpackers", :photo=>"//a.hwstatic.com/propertyimages/7/70909/98_30.jpg", :address=>"9 Paul Street London", :price_cents=> (900..2400).to_a.sample, pets: false, female_only: false, alcohol: false)
 # Hostel.create!(:name=>"The Walrus Hostel", :photo=>"//a.hwstatic.com/propertyimages/5/58378/5035_30.jpg", :address=>"10 Gosset Street, London", :price_cents=> (900..2400).to_a.sample, pets: true, female_only: true, alcohol: true)
 # Hostel.create!(:name=>"St Christopher's Inn - London Bridge", :photo=>"//a.hwstatic.com/propertyimages/5/503/501_30.jpg", :address=>"24 Cheshire Street, London", :price_cents=> (900..2400).to_a.sample, pets: false, female_only: true, alcohol: true)
 # Hostel.create!(:name=>"Hootananny Hostel", :photo=>"//a.hwstatic.com/propertyimages/2/24068/48_30.jpg", :address=>"95 Effra Road, Brixton", :price_cents=> (900..2400).to_a.sample, pets: true, female_only: true, alcohol: false)
 # Hostel.create!(:name=>"Spacious 1 Bed Apartment with River Thames Views", :photo=>"//a.hwstatic.com/propertyimages/2/272107/28_30.jpg", :address=>"18 Dwyer House, 2 Townmead Road, Fulham", :price_cents=> (900..2400).to_a.sample, pets: true, female_only: true, alcohol: false)
 # Hostel.create!(:name=>"Generator Hostel London", :photo=>"//a.hwstatic.com/propertyimages/5/510/371_30.jpg", :address=>"Compton Place, Off 37 Tavistock Place, WC1", :price_cents=> (900..2400).to_a.sample, pets: false, female_only: false, alcohol: true)
 # Hostel.create!(:name=>"Wombats City Hostel London", :photo=>"//a.hwstatic.com/propertyimages/8/88047/40_30.jpg", :address=>"7 Dock Street, London", :price_cents=> (900..2400).to_a.sample, pets: true, female_only: true, alcohol: true)
 # Hostel.create!(:name=>"Rest Up London", :photo=>"//a.hwstatic.com/propertyimages/6/62036/138_30.jpg", :address=>"172 New Kent Road", :price_cents=> (900..2400).to_a.sample, pets: false, female_only: false, alcohol: false)
 # Hostel.create!(:name=>"Hostel One Camden", :photo=>"//a.hwstatic.com/propertyimages/2/283734/35_30.jpg", :address=>"2 Southampton Rd, Belsize Park", :price_cents=> (900..2400).to_a.sample, pets: true, female_only: false, alcohol: true)
 # Hostel.create!(:name=>"SoHostel", :photo=>"//a.hwstatic.com/propertyimages/9/92473/58_30.jpg", :address=>"91 Dean Street, Soho, Westminster", :price_cents=> (900..2400).to_a.sample, pets: false, female_only: true, alcohol: true)
 # Hostel.create!(:name=>"London Waterloo Hostel", :photo=>"//a.hwstatic.com/propertyimages/3/39493/26_30.jpg", :address=>"73 Lambeth Walk, London", :price_cents=> (900..2400).to_a.sample, pets: false, female_only: true, alcohol: true)
 # Hostel.create!(:name=>"Clink261", :photo=>"//a.hwstatic.com/propertyimages/5/516/114_30.jpg", :address=>"261-265 Grays Inn Road, Kings Cross", :price_cents=> (900..2400).to_a.sample, pets: false, female_only: true, alcohol: false)
 # Hostel.create!(:name=>"Astor Museum Inn", :photo=>"//a.hwstatic.com/propertyimages/5/520/5017_30.jpg", :address=>"27 Montague Street, Bloomsbury", :price_cents=> (900..2400).to_a.sample, pets: true, female_only: true, alcohol: true)
 # Hostel.create!(:name=>"St Christopher's Village", :photo=>"//a.hwstatic.com/propertyimages/5/502/57_30.jpg", :address=>"165 Borough High Street", :price_cents=> (900..2400).to_a.sample, pets: true, female_only: true, alcohol: false)
 # Hostel.create!(:name=>"Keystone House Kings Cross", :photo=>"//a.hwstatic.com/propertyimages/4/43465/5025_30.jpg", :address=>"272-276 Pentonville Road Kings Cross, London", :price_cents=> (900..2400).to_a.sample, pets: true, female_only: true, alcohol: true)
 # Hostel.create!(:name=>"Astor Victoria", :photo=>"//a.hwstatic.com/propertyimages/5/524/5046_30.jpg", :address=>"71 Belgrave Road, Victoria", :price_cents=> (900..2400).to_a.sample, pets: false, female_only: false, alcohol: false)
 # Hostel.create!(:name=>"Astor Kensington", :photo=>"//a.hwstatic.com/propertyimages/5/523/31_30.jpg", :address=>"45 Queensborough Terrace, Bayswater", :price_cents=> (900..2400).to_a.sample, pets: true, female_only: true, alcohol: true)
 # Hostel.create!(:name=>"YHA London Oxford Street", :photo=>"//a.hwstatic.com/propertyimages/6/6996/31_30.jpg", :address=>"3 South Pl, London EC2M 2AF", :price_cents=> (900..2400).to_a.sample, pets: true, female_only: false, alcohol: false)


 # Hostel.create!(:name=>"Via Limehouse", :photo=>"//a.hwstatic.com/propertyimages/1/100584/502_30.jpg", :address=>"2A Worship St, London EC2A 2AH", :price_cents=> (900..2400).to_a.sample, pets: false, female_only: false, alcohol: false)
 Hostel.create!(:name=>"Phoenix Hostel", :photo=>"//a.hwstatic.com/propertyimages/4/48221/501_30.jpg", :address=>"Leonard St, London EC2A 4RH", :price_cents=> (900..2400).to_a.sample, pets: true, female_only: true, alcohol: true)
 Hostel.create!(:name=>"The Dictionary Hostel, Shoreditch, London", :photo=>"//a.hwstatic.com/propertyimages/6/61178/5032_30.jpg", :address=>"10-20 Kingsland Road", :price_cents=> (900..2400).to_a.sample, pets: true, female_only: false, alcohol: true)
 Hostel.create!(:name=>"MEININGER London Hyde Park", :photo=>"//a.hwstatic.com/propertyimages/1/17414/131_30.jpg", :address=>"Gosset Street, London EC2A 4JA", :price_cents=> (900..2400).to_a.sample, pets: true, female_only: false, alcohol: false)
 Hostel.create!(:name=>"St Christopher's", :photo=>"//a.hwstatic.com/propertyimages/2/20976/506_30.jpg", :address=>"Cheshire Street,London", :price_cents=> (900..2400).to_a.sample, pets: true, female_only: false, alcohol: false)
 # Hostel.create!(:name=>"St Christopher's Camden", :photo=>"//a.hwstatic.com/propertyimages/5/505/37_30.jpg", :address=>"4115 Royal Oak Court, Hoxton, London N1 6ES", :price_cents=> (900..2400).to_a.sample, pets: false, female_only: true, alcohol: true)
 # Hostel.create!(:name=>"The Birds Hostel", :photo=>"//a.hwstatic.com/propertyimages/2/283866/13_30.jpg", :address=>"4, 122 East Rd, Hoxton, London N1 6FB", :price_cents=> (900..2400).to_a.sample, pets: false, female_only: true, alcohol: false)
 Hostel.create!(:name=>"YHA London Central", :photo=>"//a.hwstatic.com/propertyimages/2/23598/5015_30.jpg", :address=>"192-196 Hanbury St, Mile End, London E1 5HU", :price_cents=> (900..2400).to_a.sample, pets: false, female_only: false, alcohol: false)
 # Hostel.create!(:name=>"No.8 Seven Sisters", :photo=>"//a.hwstatic.com/propertyimages/9/91108/1_30.jpg", :address=>"1 Great Winchester St, London EC2N 2DB", :price_cents=> (900..2400).to_a.sample, pets: false, female_only: false, alcohol: true)
 Hostel.create!(:name=>"No.8 Willesden Hostel London", :photo=>"//a.hwstatic.com/propertyimages/1/18420/12_30.jpg", :address=>"49 Chiswell St, London EC1Y 4SA", :price_cents=> (900..2400).to_a.sample, pets: false, female_only: true, alcohol: false)
 Hostel.create!(:name=>"Via London", :photo=>"//a.hwstatic.com/propertyimages/2/265813/23_30.jpg", :address=>"20 Philpot Lane, London EC3M 8AF", :price_cents=> (900..2400).to_a.sample, pets: true, female_only: true, alcohol: false)

 Hostel.create!(:name=>"Central Hostel", :photo=>"//a.hwstatic.com/propertyimages/5/5159/5025_30.jpg", :address=>"Brick Lane, London", :price_cents=> (900..2400).to_a.sample, pets: true, female_only: false, alcohol: true)
 Hostel.create!(:name=>"Barmy Badger Backpackers", :photo=>"//a.hwstatic.com/propertyimages/6/64746/9_30.jpg", :address=>"Old Street, London", :price_cents=> (900..2400).to_a.sample, pets: true, female_only: false, alcohol: true)
 # Hostel.create!({:name=>"Abercorn House", :photo=>"//a.hwstatic.com/propertyimages/3/34216/1_30.jpg", :address=>"28 Bute Gardens, Hammersmith", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"YHA London St Pancras", :photo=>"//a.hwstatic.com/propertyimages/7/7010/24_30.jpg", :address=>"79-81 Euston Road", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"St Christopher's Greenwich", :photo=>"//a.hwstatic.com/propertyimages/5/501/48_30.jpg", :address=>"189 Greenwich High Road, Greenwich", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Destinations at The Rose & Crown", :photo=>"//a.hwstatic.com/propertyimages/6/62973/10_30.jpg", :address=>"65 Union Street, Borough", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Smart Russell Square Hostel", :photo=>"//a.hwstatic.com/propertyimages/2/29412/5022_30.jpg", :address=>"71 Guilford Street, London", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Pickwick Hall", :photo=>"//a.hwstatic.com/propertyimages/7/7502/1_30.jpg", :address=>"7 Bedford Place, Bloomsbury", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Dover Castle Hostel and Bar", :photo=>"//a.hwstatic.com/propertyimages/5/530/3_30.jpg", :address=>"6a Great Dover Street", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"The Hurdwick", :photo=>"//a.hwstatic.com/propertyimages/2/285882/35_30.jpg", :address=>"2 Hurdwick Place", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"St Christopher's Shepherds Bush", :photo=>"//a.hwstatic.com/propertyimages/5/506/41_30.jpg", :address=>"Belushis Bar, 13-15 Shepherds Bush Green.", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"The Horse and Stables", :photo=>"//a.hwstatic.com/propertyimages/8/81959/501_30.jpg", :address=>"124 Westminster Bridge Road, London", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"St Christopher's Oasis-Female Only", :photo=>"//a.hwstatic.com/propertyimages/5/504/23_30.jpg", :address=>"163 Borough High Street, SE1 1HR, Southwark", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"YHA London St Pauls", :photo=>"//a.hwstatic.com/propertyimages/6/6977/12_30.jpg", :address=>"36 Carter Lane, EC4V 5AB", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Home London", :photo=>"//a.hwstatic.com/propertyimages/8/8364/19_30.jpg", :address=>"54-58 Caledonian Road, Kings Cross", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Queen Elizabeth Chelsea", :photo=>"//a.hwstatic.com/propertyimages/5/50443/5023_30.jpg", :address=>"58 Bagleys Lane", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Pride of Paddington", :photo=>"//a.hwstatic.com/propertyimages/4/48393/503_30.jpg", :address=>"1-3 Craven Road, Paddington", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Hostel One Notting Hill", :photo=>"//a.hwstatic.com/propertyimages/2/291433/34_30.jpg", :address=>"63 Prince's Square", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Venture Hostel", :photo=>"//a.hwstatic.com/propertyimages/1/14746/77_30.jpg", :address=>"86 Tanner's Hill, Deptford", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Smart Hyde Park View Hostel", :photo=>"//a.hwstatic.com/propertyimages/8/8069/1_30.jpg", :address=>"16 Leinster Terrace W2 3EU", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Green Rooms", :photo=>"//a.hwstatic.com/propertyimages/2/271479/1_30.jpg", :address=>"13-27 Station Road, Wood Green", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Atlas Hostels", :photo=>"//a.hwstatic.com/propertyimages/7/79008/23_30.jpg", :address=>"16 Talbot Square, Paddington", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Smart Hyde Park Inn Hostel", :photo=>"//a.hwstatic.com/propertyimages/5/517/502_30.jpg", :address=>"48 - 50 Inverness Terrace, Bayswater", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Prime Backpackers Angel", :photo=>"//a.hwstatic.com/propertyimages/9/93902/7_30.jpg", :address=>"Baggies Angel, 333 City Road", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Strand Continental", :photo=>"//a.hwstatic.com/propertyimages/5/51118/504_30.png", :address=>"143 Strand, London", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"PubLove @ The Crown, Battersea", :photo=>"//a.hwstatic.com/propertyimages/6/60336/78_30.jpg", :address=>"102 Lavender Hill,, Battersea", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Aquarius Hotel", :photo=>"//a.hwstatic.com/propertyimages/2/278554/1_30.jpg", :address=>"20-22 Hogarth Road", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Smart Camden Inn Hostel", :photo=>"//a.hwstatic.com/propertyimages/5/596/2_30.jpg", :address=>"55/57 Bayham Street, Camden", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"The Backpackshack", :photo=>"//a.hwstatic.com/propertyimages/6/63112/5017_30.jpg", :address=>"1 Mill Hill Road, The Talbot Pub, W3 8JB", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"New Cross Inn Hostel", :photo=>"//a.hwstatic.com/propertyimages/1/15204/11_30.jpg", :address=>"323 New Cross Road", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"PubLove @ The Green Man, Paddington", :photo=>"//a.hwstatic.com/propertyimages/2/21953/21_30.jpg", :address=>"308 Edgware Road", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"YHA London Thameside", :photo=>"//a.hwstatic.com/propertyimages/7/7000/11_30.jpg", :address=>"20 Salter Road, Rotherhithe,", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"PubLove @ The White Ferry, Victoria", :photo=>"//a.hwstatic.com/propertyimages/3/39761/2_30.jpg", :address=>"1a Sutherland Street, Victoria", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"PubLove @ The Exmouth Arms, Euston", :photo=>"//a.hwstatic.com/propertyimages/9/93796/3_30.jpg", :address=>"1 Starcross Street", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Chelsea House Hotel", :photo=>"//a.hwstatic.com/propertyimages/3/35496/1_30.jpg", :address=>"No.96 Redcliffe Gardens, Earls Court", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"The Lodge at Crystal Palace", :photo=>"//a.hwstatic.com/propertyimages/4/46276/23_30.jpg", :address=>"Crystal Palace National Sports Centre, Upper Norwood", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"PubLove @ The Steam Engine, Waterloo", :photo=>"//a.hwstatic.com/propertyimages/2/29389/2_30.jpg", :address=>"41-42 Cosser St", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Antigallican Hotel", :photo=>"//a.hwstatic.com/propertyimages/1/18780/10_30.jpg", :address=>"428 Woolwich Road", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"The Finnish Church in London", :photo=>"//a.hwstatic.com/propertyimages/8/80791/4_30.jpg", :address=>"33 Albion Street, Rotherhithe", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Blue Skies Hostel", :photo=>"//a.hwstatic.com/propertyimages/4/48530/5_30.jpg", :address=>"7 Station Rise, London", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Kensal Green Backpackers", :photo=>"//a.hwstatic.com/propertyimages/4/4483/4_30.jpg", :address=>"639 Harrow Road", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Chester Hotel Victoria", :photo=>"//a.hwstatic.com/propertyimages/2/24750/1_30.jpg", :address=>"27-29 Longmoore Street, Victoria", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"YHA London Earls Court", :photo=>"//a.hwstatic.com/propertyimages/6/6981/2_30.jpg", :address=>"38 Bolton Gardens, SW5 0AQ", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Jaeger Acton Hostel", :photo=>"//a.hwstatic.com/propertyimages/1/15584/4_30.jpg", :address=>"50, Acton High street, Acton", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Heathrow Hostel", :photo=>"//a.hwstatic.com/propertyimages/6/64089/1_30.jpg", :address=>"198 Kingsley Road, Heathrow", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Le Junction Hostel - Pub & Garden", :photo=>"//a.hwstatic.com/propertyimages/9/90013/5_30.jpg", :address=>"47 Station road, London", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Hotel Bluebells", :photo=>"//a.hwstatic.com/propertyimages/9/96186/1_30.jpg", :address=>"14 Pembridge Square, Notting Hill Gate", :price_cents=> (900..2400).to_a.sample})
 # puts "halfway"
 # Hostel.create!({:name=>"PubLove @ The Great Eastern, Greenwich", :photo=>"//a.hwstatic.com/propertyimages/4/48268/3_30.jpg", :address=>"1 Glenaffric Avenue", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"The Ambassador Heathrow Hotel", :photo=>"//a.hwstatic.com/propertyimages/2/21896/2_30.jpg", :address=>"10 Hanworth Road, Feltham,Middlesex, Heathrow", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Enrico Hotel", :photo=>"//a.hwstatic.com/propertyimages/5/5585/1_30.jpg", :address=>"77-79 Warwick Way, Victoria", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Northfields Hostel", :photo=>"//a.hwstatic.com/propertyimages/3/34115/1_30.jpg", :address=>"264 Northfield Avenue, London", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Central Park Hotel", :photo=>"//a.hwstatic.com/propertyimages/2/284176/2_30.jpg", :address=>"3-15 Wilberforce Road, Finsbury Park", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Marble Arch Inn", :photo=>"//a.hwstatic.com/propertyimages/1/13337/2_30.jpg", :address=>"49-50 Upper Berkeley Street, Marble Arch", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Kip Hotel", :photo=>"//a.hwstatic.com/propertyimages/2/266789/1_30.jpg", :address=>"2 Aspland Grove", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Hyde Park Court Hotel", :photo=>"//a.hwstatic.com/propertyimages/5/5107/4_30.jpg", :address=>"48 Norfolk Square", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Tony's House Hotel", :photo=>"//a.hwstatic.com/propertyimages/8/8503/2_30.jpg", :address=>"30 Norfolk Square, Hyde Park", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Arinza Hotel", :photo=>"//a.hwstatic.com/propertyimages/2/266580/1_30.jpg", :address=>"50 Mansfield Rd, Ilford, Essex", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Balham Lodge", :photo=>"//a.hwstatic.com/propertyimages/1/19933/5_30.jpg", :address=>"204 Bedford Hill, London", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Hyde Park Superior Apartments", :photo=>"//a.hwstatic.com/propertyimages/2/271903/1_30.jpg", :address=>"34 & 55 Inverness Terrace, Bayswater", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"London Town Hotel", :photo=>"//a.hwstatic.com/propertyimages/3/32376/2_30.jpg", :address=>"15 Penywern Road, Earls Court", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Elmwood Hotel", :photo=>"//a.hwstatic.com/propertyimages/3/34338/8_30.jpg", :address=>"19 & 20 Argyle square, London", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Fairway Hotel", :photo=>"//a.hwstatic.com/propertyimages/8/81121/9_30.jpg", :address=>"15 Argyle Street, London", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"The Crystal Lodge Hotel", :photo=>"//a.hwstatic.com/propertyimages/9/96148/15_30.jpg", :address=>"49 Brigstock Road", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"City Hotel Carlton", :photo=>"//a.hwstatic.com/propertyimages/2/27551/4_30.jpg", :address=>"90 Belgrave Road, Victoria", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Kensington West", :photo=>"//a.hwstatic.com/propertyimages/2/21368/2_30.jpg", :address=>"25 Matheson Road, Kensington", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"The Dover", :photo=>"//a.hwstatic.com/propertyimages/2/267341/1_30.jpg", :address=>"44 Belgrave Road", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Best Western Boltons London Kensington", :photo=>"//a.hwstatic.com/propertyimages/2/266666/1_30.JPG", :address=>"19-21 Penywern Road", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Hanover Hotel", :photo=>"//a.hwstatic.com/propertyimages/6/6252/2_30.jpg", :address=>"30 St. Georges Drive, Victoria", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Surtees", :photo=>"//a.hwstatic.com/propertyimages/1/13266/2_30.jpg", :address=>"94 Warwick Way, London", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Beaconsfield", :photo=>"//a.hwstatic.com/propertyimages/1/11708/501_30.jpg", :address=>"357 - 359 Green Lanes", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Lord Kensington Hotel", :photo=>"//a.hwstatic.com/propertyimages/8/8781/7_30.jpg", :address=>"38 Trebovir Road, Earls Court", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Imperial Court Suites", :photo=>"//a.hwstatic.com/propertyimages/2/270842/1_30.jpg", :address=>"81-83 Inverness Terrace, Bayswater", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Belgrave Hotel London", :photo=>"//a.hwstatic.com/propertyimages/2/268771/1_30.jpg", :address=>"9-13 Clapham Road, Oval", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Revive Lodge", :photo=>"//a.hwstatic.com/propertyimages/3/30189/1_30.jpg", :address=>"89 Hounslow Road, Feltham, Middlesex", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"London Wembley International Hotel", :photo=>"//a.hwstatic.com/propertyimages/2/26351/4_30.jpg", :address=>"Empire Way, Wembley, Middlesex", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Ridgeway Hotel", :photo=>"//a.hwstatic.com/propertyimages/8/82826/2_30.jpg", :address=>"115-117, The Ridgeway, North Chingford", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Curzon House Hotel", :photo=>"//a.hwstatic.com/propertyimages/7/7240/5_30.jpg", :address=>"58 Courtfield Gardens, West End", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Royal Hyde Park Hotel", :photo=>"//a.hwstatic.com/propertyimages/3/34048/2_30.jpg", :address=>"106/110 Queensway, London", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Goddis Lodge", :photo=>"//a.hwstatic.com/propertyimages/7/70632/4_30.JPG", :address=>"126 New Cross Road, London, SE14 5BA", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Vegas Hotel", :photo=>"//a.hwstatic.com/propertyimages/8/8267/1_30.jpg", :address=>"104 Warwick way, Victoria", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Astor Court Hotel", :photo=>"//a.hwstatic.com/propertyimages/5/58809/2_30.jpg", :address=>"20, Hallam Street., London. W1W 6JQ. UK", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Princes Square Hotel", :photo=>"//a.hwstatic.com/propertyimages/3/35590/10_30.jpg", :address=>"23-25 Princes Square,Off Ilchester Gardens, Baywater", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"London House Hotel", :photo=>"//a.hwstatic.com/propertyimages/5/529/2_30.jpg", :address=>"81 Kensington Garden Square, Bayswater W2 4DJ", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"London Backpackers", :photo=>"//a.hwstatic.com/propertyimages/5/527/25_30.JPG", :address=>"8/10 Queens Parade, Queens Road, Hendon Central", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"The London Home Hostel", :photo=>"//a.hwstatic.com/propertyimages/8/80690/6_30.jpg", :address=>"39 Chatsworth Road, London", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Park Villa", :photo=>"//a.hwstatic.com/propertyimages/9/98066/5029_30.jpg", :address=>"51 Grove Road, Bow", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"247london Hostel and Private Rooms", :photo=>"//a.hwstatic.com/propertyimages/6/64523/1_30.jpg", :address=>"37 Chatworth Road, London", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Budget London Apartments", :photo=>"//a.hwstatic.com/propertyimages/1/11493/7_30.jpg", :address=>"30 Chatsworth Rd., Willesden Green", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"ALL STAR PRIVATE STUDIOS", :photo=>"//a.hwstatic.com/propertyimages/2/24709/1_30.jpg", :address=>"Willesden Green", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Mapesbury Hostel", :photo=>"//a.hwstatic.com/propertyimages/1/19667/21_30.jpg", :address=>"39 Chatsworth Road, London", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"247 London Studios", :photo=>"//a.hwstatic.com/propertyimages/8/84154/4_30.jpg", :address=>"47 Brondesbury Park", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Dean Court", :photo=>"//a.hwstatic.com/propertyimages/1/101860/5035_30.jpg", :address=>"57 Inverness, Terrace, Bayswater", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"OneRoom", :photo=>"//a.hwstatic.com/propertyimages/2/290503/49_30.jpg", :address=>"12 Selsdon Road", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Euro Hotel Hammersmith", :photo=>"//a.hwstatic.com/propertyimages/8/83156/4_30.jpg", :address=>"31 Shepherds Bush Road, Hammersmith", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Kings Cross Guesthouse", :photo=>"//a.hwstatic.com/propertyimages/8/81486/2_30.jpg", :address=>"36 E Outram place, London", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Rowan Park Lodge", :photo=>"//a.hwstatic.com/propertyimages/6/64300/1_30.jpg", :address=>"18 Jack Dimmer Close", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Access Kensington Olympia", :photo=>"//a.hwstatic.com/propertyimages/2/272716/1_30.jpg", :address=>"7A North End Road, London", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Victor Hotel", :photo=>"//a.hwstatic.com/propertyimages/7/76699/2_30.jpg", :address=>"51 Belgrave Road, Victoria", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Access Euston", :photo=>"//a.hwstatic.com/propertyimages/2/274828/2_30.jpg", :address=>"209 North Gower Street, London", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Access Paddington", :photo=>"//a.hwstatic.com/propertyimages/2/274823/13_30.jpg", :address=>"5 Praed Street", :price_cents=> (900..2400).to_a.sample})
 # Hostel.create!({:name=>"Access Maida Vale", :photo=>"//a.hwstatic.com/propertyimages/2/274827/4_30.jpg", :address=>"31 Clifton Gardens, Maida Vale", :price_cents=> (900..2400).to_a.sample})


 Service.create!(title: "The Trussell Trust", address: "14 Liverpool Street, London", category: "Food Bank"  , description:"Provides hot food/drinks" )
 Service.create!(title: "Whitechapel Mission", address: "83 Bury Court, London", category: "Food Bank" , description: " Free meals with tea, coffee or soft drink.")
 Service.create!(title: "Helping Hand", address: "3 Clapham Road, London", category: "Food Bank"  , description:"Provides filling warm meal and shelter")
 Service.create!(title: "Hope", address: "4 Clipstone Street, London", category: "Clothes" , description: "Laundry, clothing and general goods store")
 Service.create!(title: "Clothes for good", address: "50 Great Dover St, London SE1 4YG", category: "Clothes" , description: "Donated clean clothes.")
 Service.create!(title: "Pathways", address: "4 Rawlings Street,London", category: "Clothes" , description:"Free clothes bank with laundry and hot showers." )
 Service.create!(title: "Housing Needs", address: "43 Campden Street, London", category: "Housing" , description:"Advice and assistance, including advice on housing options." )
 Service.create!(title: "Housing Advice Service", address: "98b St. Paul St, London, N1 7DF", category: "Housing" , description: "Homelessness prevention, general housing advice and information.")
 Service.create!(title: "Roof", address: "813 Wandsworth Rd, London SW8 3JH", category: "Housing" , description:"Support and advice on housing options" )
 Service.create!(title: "The Passage Day Centre", address: "1 Redchurch Street, London, E2 7DJ ", category: "Day Centre" , description:"For people aged 16+. Call 02079257895 for outreach.")
 Service.create!(title: "Rest Here", address: "237 Record St, London SE15 1TL ", category: "Day Centre" , description:"Specialist for those suffering with substance abuse. Call 02072271673 for outreach.")
 Service.create!(title: "Break Street", address: "81 Chatsworth Rd, London E5 0LH", category: "Day Centre" , description:"For people aged 16+ needing support. " )
 Service.create!(title: "St Martin's Day Centre", address: "12 Loftus Road, London ", category: "Day Centre" , description: "Day centre and support services for single homeless people.")


 Service.create!(title: "St Austel Health", address: "142, Edgware Road, London", category: "Health Service" , description:"Emergency appointments for homeless people." )
 Service.create!(title: "North Medical", address: "20 Lothrop Street, London", category: "Health Service" , description:"General health checks and advice" )
 Service.create!(title: "Southbank Drop-in", address: "74 Westow St, London SE19 3AF", category: "Health Service" , description:"Drop-in appointments 24hr" )
 Service.create!(title: "Step Up", address: "18 Chalton Street, London", category: "Job Centre" , description: "Support around job search, CV writing and interview techniques")
 Service.create!(title: "Helping Hand Angel", address: "207 Upper St, London, N1 1RL", category: "Job Centre" , description: "Career and Education advice and support 16+")
 Service.create!(title: "On Track", address: "151 East Ferry Rd, Isle of Dogs, London E14 3BT", category: "Job Centre" , description: "Helping homeless people get back on thier career path")
 Service.create!(title: "Animal Care Centre", address: "33 Camberwell Road, London", category: "Vet Services" , description: "Check-ups and temporary shelter for pets")
 Service.create!(title: "Paws", address: "5 Eaton Place, London", category: "Vet Services" , description: "Washes, checkups and food for pets of homeless people")
 Service.create!(title: "Street Vet", address: "138 Kennington Park Rd, Kennington, London SE11 4JD", category: "Vet Services" , description: "Meals and shelter for homeless people and their pets")
 Service.create!(title: "St Mungo's", address: "6 Bramber Road, London", category: "Outreach" , description: "Advice and referrals to treatment for substance misuse.")
 Service.create!(title: "London Street Angels", address: "2 Charterhouse Street, London", category: "Outreach" , description: "Street outreach team supporting people sleeping rough.")
 Service.create!(title: "Street Team", address: "36 Ironmonger Lane, London", category: "Food Bank" , description: "Support, food and clothing.")



  puts "Created #{Hostel.count} hostels and #{Service.count} services"
